name: liboqs-java CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  repository_dispatch:
    types: ["**"]

jobs:
  workflowcheck:
    name: Check validity of GitHub workflows
    runs-on: ubuntu-latest
    container: openquantumsafe/ci-ubuntu-latest:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ensure GitHub actions are valid
        run: actionlint -shellcheck ""

  linux:
    needs: workflowcheck
    runs-on: ubuntu-latest
    container: openquantumsafe/ci-ubuntu-latest:latest
    steps:
      - name: Checkout liboqs-java
        uses: actions/checkout@v4
      - name: Checkout liboqs main
        uses: actions/checkout@v4
        with:
          repository: open-quantum-safe/liboqs
          path: liboqs
          ref: main
      - name: Build liboqs
        run: mkdir build && cd build && cmake .. -G"Ninja" -DBUILD_SHARED_LIBS=ON -DOQS_BUILD_ONLY_LIB=ON && ninja install
        working-directory: liboqs
      - name: Resolve all Maven dependencies
        run: mvn dependency:go-offline
      - name: Build liboqs-java and run tests
        run: export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib" && mvn package
      - name: Compile KEM, Signatures, and Rand examples
        run: |
          javac -cp target/liboqs-java.jar examples/KEMExample.java
          javac -cp target/liboqs-java.jar examples/SigExample.java
          javac -cp target/liboqs-java.jar examples/RandExample.java
      - name: Set up Maven settings
        run: |
                    mkdir -p ~/.m2
                    echo "<settings>
                      <servers>
                        <server>
                          <id>github</id>
                          <username>${{ github.actor }}</username>
                          <password>${{ secrets.AUTH_TOKEN }}</password>
                        </server>
                      </servers>
                    </settings>" > ~/.m2/settings.xml
      - name: publish to github packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}

  macos:
    needs: workflowcheck
    runs-on: macos-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout liboqs-java
        uses: actions/checkout@v4
      - name: Checkout liboqs main
        uses: actions/checkout@v4
        with:
          repository: open-quantum-safe/liboqs
          path: liboqs
          ref: main
      - name: Install liboqs dependencies
        run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja && pip3 install -r .github/workflows/requirements.txt
        working-directory: liboqs
      - name: Build liboqs
        run: mkdir build && cd build && cmake .. -G"Ninja" -DBUILD_SHARED_LIBS=ON -DOQS_BUILD_ONLY_LIB=ON && sudo ninja install
        working-directory: liboqs
      - name: Resolve all Maven dependencies
        run: mvn dependency:go-offline
      - name: Build liboqs-java and run tests
        run: export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/usr/local/lib" && mvn -P macosx package
      - name: Compile KEM, Signatures, and Rand examples
        run: |
          javac -cp target/liboqs-java.jar examples/KEMExample.java
          javac -cp target/liboqs-java.jar examples/SigExample.java
          javac -cp target/liboqs-java.jar examples/RandExample.java
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_PAT }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: publish to github packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
